import mongoose from 'mongoose';
const { Schema } = mongoose;

const userSchema = new Schema({
    // User ID per user generated by the system
    userId: {
        type: String,
        required: true,
        unique: true,
    },
    // Username of the user to login to the system, unique
    username: {
        type: String,
        required: true,
        unique: true,
    },
    // name of the user if available
    name: {
        type: String,
        required: false,
    },
    // Password of the user to login to the system
    password: {
        type: String,
        required: true,
    },
    // Role of the user in the system. (Admin, Cashier, etc.)
    role: {
        type: String,
        required: true,
    },
    // Session Token of the user to keep the user logged in
    sessionToken: {
        type: String,
        default: null,
    },
    // Company ID where the user is registered
    companyId: {
        type: String,
        required: false,
    },
    // Shop ID where the user is registered
    companyName: {
        type: String,
        required: false,
    },
    // User's contact number
    tel: {
        type: String,
        required: false,
    },
    // User's address
    address: {
        type: String,
        required: false,
    },
    // User's email
    email: {
        type: String,
        required: false,
    },
    // ShopIds, If the user is a cashier,admin, superadmin this field will be assigned from the shop,
    // if the user is a customer, this field will be filled with the shopIds where the user has shopped
    shopIds: {
        type: [String],
        required: false,
    },
    // Who created the user, logged in user
    createdBy: {
        type: String,
        required: true,
    },
    // User's status (Active, Inactive)
    toggle: {
        type: String,
        default: "disable",
        enum: ["enable", "disable"],
    }
}, {
    timestamps: true
});

userSchema.pre('save', async function(next) {
    if (this.isNew) {
        const lastUser = await mongoose.model('User').findOne().sort({ createdAt: -1 });
        const lastUserID = lastUser ? parseInt(lastUser.userId.split('-')[1]) : 0;
        this.userId = `UserID-${lastUserID + 1}`;
    }
    next();
});

export default mongoose.model("User", userSchema);
